# =====================================================
# Movie data displayed on the Movie page.
#
# Each entry includes:
# - `title`: The movie's title.
# - `posterImage`: URL to the movie poster image.
# - `note`: A short personal note or description about the movie.
# =====================================================

movies:
  - title: "Half-Marathon"
    posterImage: "https://Li-Zou.github.io/my-website/images/running.jpg"
    note: "[Movie Description]"

  - title: "Fitness"
    posterImage: "https://Li-Zou.github.io/my-website/images/fitness.jpg"
    note: "[Movie Description]"

  - title: "Reading"
    posterImage: "https://Li-Zou.github.io/my-website/images/minimalisam.png"
    note: "[Movie Description]"

  #- title: "The Shawshank Redemption"
  #  posterImage: "https://media.themoviedb.org/t/p/w440_and_h660_face/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg"
  #  note: "A timeless story of hope and perseverance that reminds me to stay resilient, no matter the odds."


