# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Li Zou"
  headline: "Machine Learning Scientist"
  email: "L.Zou@tudelft.nl"
  location: Delft, Netherlands
  profileImage: "/images/LiZou1.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/li-zou-83b367279"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=wDsWlTYAAAAJ&hl=en"
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    #- name: "R√©sum√©"
    #  url: "/pdf/sample-resume.pdf"
    #  icon:
    #    name: "FaRegIdBadge"
    #    package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/Li-Zou?tab=repositories"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

    #- name: "Facebook"
    #  url: "https://www.facebook.com/[your-facebook]"
    #  icon:
    #    name: "FaSquareFacebook"
    #    package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I‚Äôm currently a ML scientist at the Haptic Interface Technology Lab in Delft. My work focuses on developing AI models to classify materials and uncover the underlying mechanisms of tactile perception.
    <div class="my-2"></div>

    I hold a PhD in Computer Science from TU Delft, with a focus on Network Science and Machine Learning. My research was conducted within the Multimedia Computing Group, under the supervision of Dr. Huijuan Wang and Prof. Alan Hanjalic. 
    
    <div class="my-2"></div>
    I love working with AI and data. I enjoy using tools from mathematics, machine learning, deep learning and programming to analyze data, uncover patterns, and generate insights that support decision-making. 
    This process excites me and continually motivates me to learn new tools and technologies. 
    
    <div class="my-2"></div>
    Outside of work, I enjoy running marathons, playing badminton, fitness training, and cycling, which inspire creativity and keep me energized. 
    
    <div class="my-2"></div>
    Thanks for visiting! Feel free to <a href="mailto:[L.Zou@tudelft.nl]" target="_blank" rel="noopener noreferrer">reach out</a> to connect.


    
# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "Ph.D. in AI"
    school: "Delft Univeristy of Technology"
    years: "2019 - 2024"
    logo: "/images/logo1.png"

  - degree: "M.S. in Complex Systems"
    school: "Beƒ≥ing Normal University"
    years: "2016 - 2019"
    logo: "/images/logo1.png"

  - degree: "B.S. in Mathematics and Applied Mathematics"
    school: "Chengdu University of Technology"
    years: "2011 - 2015"
    logo: "/images/logo1.png"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: " Machine Learning Scientist"
    company: "Haptic Interface Technology Lab"
    years: "Oct 2024 - Present"
    logo: "/images/logo1.png"

  - title: "Machine Learning Engineering Intern"
    company: "Energy Quant Research Institution"
    years: "Oct 2025 - Present"
    logo: "/images/logo1.png"

  - title: "Consultant"
    company: "Xueda Education Technology Group Co., Ltd."
    years: "Jul 2015 - Sep 2016"
    logo: "/images/logo1.png"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

talks:
  - category: "Conference"
    title: "AI for Haptic"
    organization: "IEEE World Haptics Conference 2025"
    date: "[Jul. 2025, Suwon, South Korea]"
    link: null
    image: null

  - category: "Conference"
    title: "Vulnerability of information transport on temporal networks to link removal"
    organization: "COMPLEX NETWORKS 2023"
    date: "[Nov. 2023, Menton Riviera, France]"
    link: https://li-zou.github.io/personal.github.io/files/slides/Poster_France.pdf
    image: null

  - category: "Conference"
    title: "Short- and long-term temporal network prediction based on network memory"
    organization: "NetSci 2023"
    date: "[Jul. 2023, Vienna, Austria]"
    link: https://li-zou.github.io/personal.github.io/files/slides/Poster1_long_term.pdf
    image: null

  - category: "Conference"
    title: "Temporal network prediction and interpretation"
    organization: "COMPLEX NETWORKS 2022"
    date: "[Nov. 2023, Palermo, Italy]"
    link: https://ieeexplore.ieee.org/abstract/document/9665319
    image: null

  - category: "Conference"
    title: "AI for temporal network prediction"
    organization: "NetSci 2022"
    date: "[Jul. 2022, Shanghai, China]"
    link: null
    image: null

  - category: "Conference"
    title: "Link prediction"
    organization: "NetSci 2019"
    date: "[May. 2019, Vermont, USA]"
    link: null
    image: null
    
  - category: "Summer School"
    title: "ACDL 2022, 5th Advanced Online & Onsite Course on Data Science & Machine Learning"
    organization: "Universit√† di Catania"
    date: "[May. 2022, Siena, Italy]"
    link: null
    image: null

  - category: "Winter School"
    title: "BigDat 2020, 6th International Winter School on Big Data"
    organization: "Universit√† Politecnica delle Marche"
    date: "[2020, Italy]"
    link: null
    image: null

  - category: "Winter School"
    title: "The BNU-ASU intensive winter school on complex system"
    organization: "Arizona State University"
    date: "[2018, USA]"
    link: null
    image: null

  #- category: "Workshop"
  #  title: "Deep Learning with Keras"
  #  organization: "University of Illinois Urbana-Champaign (UIUC)"
  #  date: "Sep 4, 2019"
  #  link: null
  #  image: "https://pm25.github.io/images/uiuc-workshop.webp"


# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

services:
  - category: "Conference"
    role: "Volunteer"
    organization: "Dutch NetSci Summer Symposium 2023"
    date: "2023"
    link: null
    image: null

  - category: "Teaching"
    role: "Teaching Assistant"
    organization: "TU Delft, Modeling and Data Analysis in Complex Network "
    date: "2021"
    link: null
    image: null

  - category: "Teaching"
    role: "Teaching Assistant"
    organization: "Beijing Normal University, Dynamic Systems Analysis "
    date: "2018"
    link: null
    image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Fluent
      description: null

    - name: "Matlab"
      logo: "/images/matlab.png"
      proficiency: Fluent
      description: null

    - name: "C++"
      logo: "/images/C.png"
      proficiency: Intermediate
      description: null

    - name: "SQL"
      logo: "https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png"
      proficiency: Fluent
      description: null

  Deep Learning:
    - name: "TensorFlow"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg"
      proficiency: Fluent
      description: null

    - name: "Keras"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
      proficiency: Fluent
      description: null
  
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
      proficiency: Intermediate
      description: null

  Machine Learning:   
    - name: "Scikit-learn"
      logo: "/images/Scikit_learn_logo_small.svg"
      proficiency: Fluent
      description: null

    - name: "Matplotlib"
      logo: "https://upload.wikimedia.org/wikipedia/commons/0/01/Created_with_Matplotlib-logo.svg"
      proficiency: Fluent
      description: null

    - name: "PySpark"
      logo: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg"
      proficiency: Intermediate
      description: null

    - name: "Pandas"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Pandas_logo.svg"
      proficiency: Fluent
      description: null

    - name: "Numpy"
      logo: "https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg"
      proficiency: Fluent
      description: null

  MLOPs:
    - name: "git"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Git-logo.svg"
      proficiency: Fluent
      description: null

    - name: "dvc"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/af/Data_Version_Control._Official_Logo_by_Iterative.ai.png"
      proficiency: Fluent
      description: null

    - name: "mlflow"
      logo: "/images/mlflow.png"
      proficiency: Intermediate
      description: null
  
    - name: "docker"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Docker_Logo.png"
      proficiency: Intermediate
      description: null

    - name: "Azure"
      logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Microsoft_Azure.svg"
      proficiency: Intermediate
      description: null


  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "Professional working proficiency."

    - name: "Chinese"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Native
      description: null

    - name: "Dutch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Beginner
      description: null
