# =====================================================
# Project data displayed on the Projects page.
#
# This section automatically fetches project information from your GitHub repositories.
#
# ✔ The `id` field should be the exact repository name
#    (e.g., from: github.com/<your-username>/<repo-name>)
#
# ✔ The `displayName` field controls how the project name appears on the website.
#
# ✔ Use the `featured` field to control which projects appear on the homepage.
#    - featured: true  → shown on the homepage
#    - featured: false → shown only on the Projects page
# =====================================================

projects:
  items:
    - id: "Deep-learning" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "Deep learning" # name that will be displayed on the website
      previewImage: https://Li-Zou.github.io/my-website/images/DL.png
      featured: true

    - id: "LLM-Build-a-Semantic-Book-Recommender" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "Use LLM to build a book recommender" # name that will be displayed on the website
      previewImage: https://Li-Zou.github.io/my-website/images/LLM_book_recommender.png
      featured: true

    - id: "showlit"
      displayName: "Showlit22"
      previewImage: https://pm25.github.io/showlit/images/full_logo.png
      featured: true

    - id: "pm25.github.io"
      displayName: "pm25.github.io"
      previewImage: null
      featured: false

