# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "my-website"
  repoUrl: "https://github.com/Li-Zou/my-website"
  description: "A short description"
  author: "Li Zou"
